
'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код был создан из шаблона.
'
'     Изменения в этом файле могут привести к неправильному поведению и будут утрачены, если
'     код создается повторно.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("5b56c492-1c5a-4608-b58c-748295714b80")>

#Region "Метаданные связи EDM"
<Assembly: EdmRelationshipAttribute("OMSModel", "FK_Orders_Customer", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Customer), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Order))>
<Assembly: EdmRelationshipAttribute("OMSModel", "FK_OrderDetail_Orders", "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Order), "OrderDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(OrderDetail))>
<Assembly: EdmRelationshipAttribute("OMSModel", "FK_OrderDetail_Product", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Product), "OrderDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(OrderDetail))>
#End Region

#Region "Контексты"
''' <summary>
''' Нет доступной документации по метаданным.
''' </summary>
Public Partial Class OMSEntities 
    Inherits ObjectContext

    #Region "Конструкторы"
    ''' <summary>
    ''' Инициализирует новый объект OMSEntities, используя строку подключения, которая находится в разделе "OMSEntities" файла конфигурации приложения.
    ''' </summary>
    Public Sub New() 
        MyBase.New("name=OMSEntities", "OMSEntities")
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Инициализировать новый объект OMSEntities.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "OMSEntities")
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Инициализировать новый объект OMSEntities.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "OMSEntities")
        OnContextCreated()
    End Sub
    #End Region
    
    #Region "Разделяемые методы"
    Partial Private Sub OnContextCreated()
    End Sub
    #End Region
    
    #Region "Свойства ObjectSet"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    Public ReadOnly Property Customers() As ObjectSet(Of Customer)
        Get
            If (_Customers Is Nothing) Then
                _Customers = MyBase.CreateObjectSet(Of Customer)("Customers")
            End If
            Return _Customers
        End Get
    End Property
    
    Private _Customers As ObjectSet(Of Customer)

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    Public ReadOnly Property OrderDetails() As ObjectSet(Of OrderDetail)
        Get
            If (_OrderDetails Is Nothing) Then
                _OrderDetails = MyBase.CreateObjectSet(Of OrderDetail)("OrderDetails")
            End If
            Return _OrderDetails
        End Get
    End Property
    
    Private _OrderDetails As ObjectSet(Of OrderDetail)

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    Public ReadOnly Property Orders() As ObjectSet(Of Order)
        Get
            If (_Orders Is Nothing) Then
                _Orders = MyBase.CreateObjectSet(Of Order)("Orders")
            End If
            Return _Orders
        End Get
    End Property
    
    Private _Orders As ObjectSet(Of Order)

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    Public ReadOnly Property Products() As ObjectSet(Of Product)
        Get
            If (_Products Is Nothing) Then
                _Products = MyBase.CreateObjectSet(Of Product)("Products")
            End If
            Return _Products
        End Get
    End Property
    
    Private _Products As ObjectSet(Of Product)
    #End Region
    #Region "Методы AddTo"
    
    ''' <summary>
    ''' Нерекомендуемый метод для добавления нового объекта к набору сущностей Customers. Вместо него рекомендуется использовать метод .Add связанного свойства ObjectSet(Of T).
    ''' </summary>
    Public Sub AddToCustomers(ByVal customer As Customer)
        MyBase.AddObject("Customers", customer)
    End Sub
    
    ''' <summary>
    ''' Нерекомендуемый метод для добавления нового объекта к набору сущностей OrderDetails. Вместо него рекомендуется использовать метод .Add связанного свойства ObjectSet(Of T).
    ''' </summary>
    Public Sub AddToOrderDetails(ByVal orderDetail As OrderDetail)
        MyBase.AddObject("OrderDetails", orderDetail)
    End Sub
    
    ''' <summary>
    ''' Нерекомендуемый метод для добавления нового объекта к набору сущностей Orders. Вместо него рекомендуется использовать метод .Add связанного свойства ObjectSet(Of T).
    ''' </summary>
    Public Sub AddToOrders(ByVal order As Order)
        MyBase.AddObject("Orders", order)
    End Sub
    
    ''' <summary>
    ''' Нерекомендуемый метод для добавления нового объекта к набору сущностей Products. Вместо него рекомендуется использовать метод .Add связанного свойства ObjectSet(Of T).
    ''' </summary>
    Public Sub AddToProducts(ByVal product As Product)
        MyBase.AddObject("Products", product)
    End Sub
    #End Region
End Class

#End Region
#Region "Сущности"
''' <summary>
''' Нет доступной документации по метаданным.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="OMSModel", Name:="Customer")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Customer 
    Inherits EntityObject
    #Region "Метод фабрики"
        
    ''' <summary>
    ''' Создать новый объект Customer.
    ''' </summary>
    ''' <param name="customerID">Начальное значение свойства CustomerID.</param>
    ''' <param name="lastName">Начальное значение свойства LastName.</param>
    ''' <param name="modified">Начальное значение свойства Modified.</param>
    Public Shared Function CreateCustomer(customerID As Global.System.Int32, lastName As Global.System.String, modified As Global.System.Byte()) As Customer
        Dim customer as Customer = New Customer
        customer.CustomerID = customerID
            
        customer.LastName = lastName
            
        customer.Modified = modified
            
        Return customer
    End Function
    #End Region
    #Region "Первичные свойства"
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CustomerID() As Global.System.Int32
        Get
            Return _CustomerID
        End Get
        Set
            If (CustomerID <> value) Then
                OnCustomerIDChanging(value)
                ReportPropertyChanging("CustomerID")
                _CustomerID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("CustomerID")
                OnCustomerIDChanged()
            End If
        End Set
    End Property
    
    Private _CustomerID as Global.System.Int32
    Private Partial Sub OnCustomerIDChanging(value As Global.System.Int32)
    End Sub
    
    Private Partial Sub OnCustomerIDChanged()
    End Sub
    
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LastName() As Global.System.String
        Get
            Return _LastName
        End Get
        Set
            OnLastNameChanging(value)
            ReportPropertyChanging("LastName")
            _LastName = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("LastName")
            OnLastNameChanged()
        End Set
    End Property
    
    Private _LastName as Global.System.String
    Private Partial Sub OnLastNameChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnLastNameChanged()
    End Sub
    
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FirstName() As Global.System.String
        Get
            Return _FirstName
        End Get
        Set
            OnFirstNameChanging(value)
            ReportPropertyChanging("FirstName")
            _FirstName = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("FirstName")
            OnFirstNameChanged()
        End Set
    End Property
    
    Private _FirstName as Global.System.String
    Private Partial Sub OnFirstNameChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnFirstNameChanged()
    End Sub
    
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Address() As Global.System.String
        Get
            Return _Address
        End Get
        Set
            OnAddressChanging(value)
            ReportPropertyChanging("Address")
            _Address = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Address")
            OnAddressChanged()
        End Set
    End Property
    
    Private _Address as Global.System.String
    Private Partial Sub OnAddressChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnAddressChanged()
    End Sub
    
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property City() As Global.System.String
        Get
            Return _City
        End Get
        Set
            OnCityChanging(value)
            ReportPropertyChanging("City")
            _City = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("City")
            OnCityChanged()
        End Set
    End Property
    
    Private _City as Global.System.String
    Private Partial Sub OnCityChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnCityChanged()
    End Sub
    
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property State() As Global.System.String
        Get
            Return _State
        End Get
        Set
            OnStateChanging(value)
            ReportPropertyChanging("State")
            _State = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("State")
            OnStateChanged()
        End Set
    End Property
    
    Private _State as Global.System.String
    Private Partial Sub OnStateChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnStateChanged()
    End Sub
    
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ZIP() As Global.System.String
        Get
            Return _ZIP
        End Get
        Set
            OnZIPChanging(value)
            ReportPropertyChanging("ZIP")
            _ZIP = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("ZIP")
            OnZIPChanged()
        End Set
    End Property
    
    Private _ZIP as Global.System.String
    Private Partial Sub OnZIPChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnZIPChanged()
    End Sub
    
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Modified() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_Modified)
        End Get
        Set
            OnModifiedChanging(value)
            ReportPropertyChanging("Modified")
            _Modified = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("Modified")
            OnModifiedChanged()
        End Set
    End Property
    
    Private _Modified as Global.System.Byte()
    Private Partial Sub OnModifiedChanging(value As Global.System.Byte())
    End Sub
    
    Private Partial Sub OnModifiedChanged()
    End Sub
    
    #End Region
    #Region "Свойства навигации"
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("OMSModel", "FK_Orders_Customer", "Orders")>
     Public Property Orders() As EntityCollection(Of Order)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Order)("OMSModel.FK_Orders_Customer", "Orders")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Order)("OMSModel.FK_Orders_Customer", "Orders", value)
            End If
        End Set
    End Property
    #End Region
End Class

''' <summary>
''' Нет доступной документации по метаданным.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="OMSModel", Name:="Order")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Order 
    Inherits EntityObject
    #Region "Метод фабрики"
        
    ''' <summary>
    ''' Создать новый объект Order.
    ''' </summary>
    ''' <param name="orderID">Начальное значение свойства OrderID.</param>
    ''' <param name="modified">Начальное значение свойства Modified.</param>
    Public Shared Function CreateOrder(orderID As Global.System.Int32, modified As Global.System.Byte()) As Order
        Dim order as Order = New Order
        order.OrderID = orderID
            
        order.Modified = modified
            
        Return order
    End Function
    #End Region
    #Region "Первичные свойства"
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property OrderID() As Global.System.Int32
        Get
            Return _OrderID
        End Get
        Set
            If (OrderID <> value) Then
                OnOrderIDChanging(value)
                ReportPropertyChanging("OrderID")
                _OrderID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("OrderID")
                OnOrderIDChanged()
            End If
        End Set
    End Property
    
    Private _OrderID as Global.System.Int32
    Private Partial Sub OnOrderIDChanging(value As Global.System.Int32)
    End Sub
    
    Private Partial Sub OnOrderIDChanged()
    End Sub
    
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property OrderDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _OrderDate
        End Get
        Set
            OnOrderDateChanging(value)
            ReportPropertyChanging("OrderDate")
            _OrderDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("OrderDate")
            OnOrderDateChanged()
        End Set
    End Property
    
    Private _OrderDate as Nullable(Of Global.System.DateTime)
    Private Partial Sub OnOrderDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub
    
    Private Partial Sub OnOrderDateChanged()
    End Sub
    
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ShipDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _ShipDate
        End Get
        Set
            OnShipDateChanging(value)
            ReportPropertyChanging("ShipDate")
            _ShipDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ShipDate")
            OnShipDateChanged()
        End Set
    End Property
    
    Private _ShipDate as Nullable(Of Global.System.DateTime)
    Private Partial Sub OnShipDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub
    
    Private Partial Sub OnShipDateChanged()
    End Sub
    
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Modified() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_Modified)
        End Get
        Set
            OnModifiedChanging(value)
            ReportPropertyChanging("Modified")
            _Modified = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("Modified")
            OnModifiedChanged()
        End Set
    End Property
    
    Private _Modified as Global.System.Byte()
    Private Partial Sub OnModifiedChanging(value As Global.System.Byte())
    End Sub
    
    Private Partial Sub OnModifiedChanged()
    End Sub
    
    #End Region
    #Region "Свойства навигации"
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("OMSModel", "FK_Orders_Customer", "Customer")>
    Public Property Customer() As Customer
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("OMSModel.FK_Orders_Customer", "Customer").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("OMSModel.FK_Orders_Customer", "Customer").Value = value
        End Set
    End Property
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property CustomerReference() As EntityReference(Of Customer)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("OMSModel.FK_Orders_Customer", "Customer")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Customer)("OMSModel.FK_Orders_Customer", "Customer", value)
            End If
        End Set
    End Property
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("OMSModel", "FK_OrderDetail_Orders", "OrderDetail")>
     Public Property OrderDetails() As EntityCollection(Of OrderDetail)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of OrderDetail)("OMSModel.FK_OrderDetail_Orders", "OrderDetail")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of OrderDetail)("OMSModel.FK_OrderDetail_Orders", "OrderDetail", value)
            End If
        End Set
    End Property
    #End Region
End Class

''' <summary>
''' Нет доступной документации по метаданным.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="OMSModel", Name:="OrderDetail")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class OrderDetail 
    Inherits EntityObject
    #Region "Метод фабрики"
        
    ''' <summary>
    ''' Создать новый объект OrderDetail.
    ''' </summary>
    ''' <param name="orderDetailID">Начальное значение свойства OrderDetailID.</param>
    ''' <param name="quantity">Начальное значение свойства Quantity.</param>
    ''' <param name="modified">Начальное значение свойства Modified.</param>
    Public Shared Function CreateOrderDetail(orderDetailID As Global.System.Int32, quantity As Global.System.Int32, modified As Global.System.Byte()) As OrderDetail
        Dim orderDetail as OrderDetail = New OrderDetail
        orderDetail.OrderDetailID = orderDetailID
            
        orderDetail.Quantity = quantity
            
        orderDetail.Modified = modified
            
        Return orderDetail
    End Function
    #End Region
    #Region "Первичные свойства"
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property OrderDetailID() As Global.System.Int32
        Get
            Return _OrderDetailID
        End Get
        Set
            If (OrderDetailID <> value) Then
                OnOrderDetailIDChanging(value)
                ReportPropertyChanging("OrderDetailID")
                _OrderDetailID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("OrderDetailID")
                OnOrderDetailIDChanged()
            End If
        End Set
    End Property
    
    Private _OrderDetailID as Global.System.Int32
    Private Partial Sub OnOrderDetailIDChanging(value As Global.System.Int32)
    End Sub
    
    Private Partial Sub OnOrderDetailIDChanged()
    End Sub
    
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Quantity() As Global.System.Int32
        Get
            Return _Quantity
        End Get
        Set
            OnQuantityChanging(value)
            ReportPropertyChanging("Quantity")
            _Quantity = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Quantity")
            OnQuantityChanged()
        End Set
    End Property
    
    Private _Quantity as Global.System.Int32
    Private Partial Sub OnQuantityChanging(value As Global.System.Int32)
    End Sub
    
    Private Partial Sub OnQuantityChanged()
    End Sub
    
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Price() As Nullable(Of Global.System.Decimal)
        Get
            Return _Price
        End Get
        Set
            OnPriceChanging(value)
            ReportPropertyChanging("Price")
            _Price = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Price")
            OnPriceChanged()
        End Set
    End Property
    
    Private _Price as Nullable(Of Global.System.Decimal)
    Private Partial Sub OnPriceChanging(value As Nullable(Of Global.System.Decimal))
    End Sub
    
    Private Partial Sub OnPriceChanged()
    End Sub
    
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Modified() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_Modified)
        End Get
        Set
            OnModifiedChanging(value)
            ReportPropertyChanging("Modified")
            _Modified = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("Modified")
            OnModifiedChanged()
        End Set
    End Property
    
    Private _Modified as Global.System.Byte()
    Private Partial Sub OnModifiedChanging(value As Global.System.Byte())
    End Sub
    
    Private Partial Sub OnModifiedChanged()
    End Sub
    
    #End Region
    #Region "Свойства навигации"
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("OMSModel", "FK_OrderDetail_Orders", "Orders")>
    Public Property Order() As Order
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Order)("OMSModel.FK_OrderDetail_Orders", "Orders").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Order)("OMSModel.FK_OrderDetail_Orders", "Orders").Value = value
        End Set
    End Property
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property OrderReference() As EntityReference(Of Order)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Order)("OMSModel.FK_OrderDetail_Orders", "Orders")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Order)("OMSModel.FK_OrderDetail_Orders", "Orders", value)
            End If
        End Set
    End Property
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("OMSModel", "FK_OrderDetail_Product", "Product")>
    Public Property Product() As Product
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("OMSModel.FK_OrderDetail_Product", "Product").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("OMSModel.FK_OrderDetail_Product", "Product").Value = value
        End Set
    End Property
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ProductReference() As EntityReference(Of Product)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("OMSModel.FK_OrderDetail_Product", "Product")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Product)("OMSModel.FK_OrderDetail_Product", "Product", value)
            End If
        End Set
    End Property
    #End Region
End Class

''' <summary>
''' Нет доступной документации по метаданным.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="OMSModel", Name:="Product")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Product 
    Inherits EntityObject
    #Region "Метод фабрики"
        
    ''' <summary>
    ''' Создать новый объект Product.
    ''' </summary>
    ''' <param name="productID">Начальное значение свойства ProductID.</param>
    ''' <param name="modified">Начальное значение свойства Modified.</param>
    Public Shared Function CreateProduct(productID As Global.System.Int32, modified As Global.System.Byte()) As Product
        Dim product as Product = New Product
        product.ProductID = productID
            
        product.Modified = modified
            
        Return product
    End Function
    #End Region
    #Region "Первичные свойства"
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ProductID() As Global.System.Int32
        Get
            Return _ProductID
        End Get
        Set
            If (ProductID <> value) Then
                OnProductIDChanging(value)
                ReportPropertyChanging("ProductID")
                _ProductID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ProductID")
                OnProductIDChanged()
            End If
        End Set
    End Property
    
    Private _ProductID as Global.System.Int32
    Private Partial Sub OnProductIDChanging(value As Global.System.Int32)
    End Sub
    
    Private Partial Sub OnProductIDChanged()
    End Sub
    
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property
    
    Private _Name as Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnNameChanged()
    End Sub
    
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Description() As Global.System.String
        Get
            Return _Description
        End Get
        Set
            OnDescriptionChanging(value)
            ReportPropertyChanging("Description")
            _Description = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Description")
            OnDescriptionChanged()
        End Set
    End Property
    
    Private _Description as Global.System.String
    Private Partial Sub OnDescriptionChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnDescriptionChanged()
    End Sub
    
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Modified() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_Modified)
        End Get
        Set
            OnModifiedChanging(value)
            ReportPropertyChanging("Modified")
            _Modified = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("Modified")
            OnModifiedChanged()
        End Set
    End Property
    
    Private _Modified as Global.System.Byte()
    Private Partial Sub OnModifiedChanging(value As Global.System.Byte())
    End Sub
    
    Private Partial Sub OnModifiedChanged()
    End Sub
    
    #End Region
    #Region "Свойства навигации"
    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("OMSModel", "FK_OrderDetail_Product", "OrderDetail")>
     Public Property OrderDetails() As EntityCollection(Of OrderDetail)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of OrderDetail)("OMSModel.FK_OrderDetail_Product", "OrderDetail")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of OrderDetail)("OMSModel.FK_OrderDetail_Product", "OrderDetail", value)
            End If
        End Set
    End Property
    #End Region
End Class

#End Region

